# NodeCheckins schema
# --- !Ups
CREATE TABLE IF NOT EXISTS "NODECHECKINS" (
    "ID" SERIAL PRIMARY KEY,
    "NODEID" bigint NOT NULL,
    "JOBID" bigint NOT NULL,
    "RESPONSECODE" int NOT NULL,
    "CREATEDAT" timestamp NOT NULL
);

INSERT INTO "NODECHECKINS" ("NODEID", "JOBID", "RESPONSECODE", "CREATEDAT")
VALUES (1, 1, 200, '2017-01-16T13:15:39.248+08:00');

INSERT INTO "NODECHECKINS" ("NODEID", "JOBID", "RESPONSECODE", "CREATEDAT")
VALUES (1, 2, 404, '2017-01-16T13:15:39.248+08:00');

# --- !Downs
DROP TABLE "NODECHECKINS";