# BruteforceJobStatus schema
# --- !Ups
CREATE TABLE IF NOT EXISTS "BRUTEFORCESTATUS" (
    "ID" SERIAL PRIMARY KEY,
    "JOBID" bigint NOT NULL,
    "NODEID" bigint NOT NULL,
    "INDEX" bigint NOT NULL,
    "CREATEDAT" timestamp NOT NULL
);

INSERT INTO "BRUTEFORCESTATUS" ( "JOBID", "NODEID", "INDEX", "CREATEDAT")
VALUES (1, 1, 1024, '2017-01-16T13:15:39.248+08:00');

INSERT INTO "BRUTEFORCESTATUS" ( "JOBID", "NODEID", "INDEX", "CREATEDAT")
VALUES (1, 1, 2048, '2017-01-16T13:15:39.248+08:00');

# --- !Downs
DROP TABLE "BRUTEFORCESTATUS";
